title: Usama Naseer - Personal webpage
author: Usama Naseer
email: usama6naseer@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Works at Bytedance, Ph.D. from Brown University.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Usama Naseer
  # tagline: Ph.D.
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  dark_mode: false # set true to add dark mode toggle

  # generate social links in footer
  social_links:
    twitter: usama6naseer
    # github:  thelehhman
    # linkedIn: in/thelehhman
    # rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
